name: Node.js CI

on:
  push:
    branches: [ "main" ]

env:
  CLERK_SECRET_KEY: "${{ secrets.CLERK_SECRET_KEY }}"
  CLERK_PUBLISHABLE_KEY: "${{ secrets.CLERK_PUBLISHABLE_KEY }}"
  MONGODB_URI: "${{ secrets.MONGODB_URI }}"
  WEBHOOK_SECRET: "${{ secrets.WEBHOOK_SECRET }}"
  OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
  GETIMGAI_API_KEY: "${{ secrets.GETIMGAI_API_KEY }}"
  CORS_ORIGIN: "${{ secrets.CORS_ORIGIN }}"
  FIREBASE_API_KEY: "${{ secrets.FIREBASE_API_KEY }}"
  FIREBASE_AUTH_DOMAIN: "${{ secrets.FIREBASE_AUTH_DOMAIN }}"
  FIREBASE_PROJECT_ID: "${{ secrets.FIREBASE_PROJECT_ID }}"
  FIREBASE_STORAGE_BUCKET: "${{ secrets.FIREBASE_STORAGE_BUCKET }}"
  FIREBASE_MESSAGING_SENDER_ID: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
  FIREBASE_APP_ID: "${{ secrets.FIREBASE_APP_ID }}"
  FIREBASE_MEASUREMENT_ID: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
  PORT: "${{ secrets.PORT }}"

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: yosefhershberg/culinary-gpt-server:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull yosefhershberg/culinary-gpt-server:latest

      - name: Delete old container
        run: docker rm -f server-container || true

      - name: Create .env file
        env:
          PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        run: echo "${{ secrets.PROD_ENV_FILE }}" > .env

      - name: Run Docker container with environment file
        run: docker run -d -p 5000:5000 --name server-container --env-file .env yosefhershberg/culinary-gpt-server:latest

      - name: Remove dangling Docker images
        run: docker image prune -f